{% set version = "0.7.4" %}

package:
  name: mapio
  version: {{ version }}

source:
  url: https://github.com/usgs/MapIO/archive/{{ version }}.tar.gz
  sha256: 2fedc7cbb7c5958e4dbea00755494123593c6c4c4402d97c5fb8f150bf62b727

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - gdal
    - h5py
    - matplotlib
    - pandas
    - rasterio
    - scipy
    - shapely

test:

  imports:
    - mapio

about:
  home: https://github.com/usgs/MapIO
  license: Public Domain
  summary: 'USGS library for dealing with gridded data (loading, interpolation, etc.)'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
