travis:
  secure:
    BINSTAR_TOKEN: hNQNfxIzPKUdwS4oVTaxEdhUuxnAJF9WJGxw1DNiDKXu3cIPOFfJheOAeKcYbD5SIcAwVTXdkYqcK+ucmRRsB5o8FyvruvXaIc4w0Mo6uuFKTknimkKOd2UyX6fz4huu5pe5F1BESm7T3zFyd5fc8RONQzHxAP7EeIGILUy3EzDYsztkNjTnPehkugAj80ffnh9u1kiy5FlIhzbBEac03UPnt1Y2SwGPAcDLTcxhW6H7oh30awszSoJtcThibrcncISTw/fHh2Kta9PIW89SMbdpcsSRcJNrjGMQRVr+qIh2pTgtHr3qgU7PHvUJYyK4p70CA1pagqT2TdOQVjt/0oj3ZOokMo7N2W2TFO9LCatWkKloRe5ed3MO8LyOxE7KuumMyG506rPkEBctlKK1khwZY0AVgwenFT2rFejxyV6XEtBXhZIdu/HeBd7NesMp9V4Y/fp/qaX5Tp5DbfP3C5otxCo5g+d8T+vXKTSaq3BCZBbCjDwsyrxeQWQhqqlv/OEy04IuDwT+aaj/AujNRuGva9cxSok7QLG7VoipXeYDUZ1Fy4Z3MxKhITLU9Ps2uKcgcaNwur/W4QY9HjKivATDH2RFPW8oK0LqZtErDYl9VGEB1/FoffJRbnwCUTtrNOlp5xV7MxpWAaXZWYlyeRGpaTrGbKU7GjLW6fofyYw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
